server:
  port: 9002
spring:
  application:
    name: service-provider-consul

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: service-provider-consul