#单机模式
server:
  port: 9200

spring:
  application:
    name: service-invoker-config-bus-rabbitmq

  #        rabbitmq
  rabbitmq:
    host: 192.168.11.100
    port: 5672
    username: admin
    password: admin