#单机模式时
server:
  port: 8600

spring:
  application:
    name: server-security-mysql
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot_oauth2?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=true&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#http编码配置
http:
  encoding:
    charset: UTF-8
    force: true
    enabled: true
