#单机模式
server:
  port: 8100
spring:
  application:
    #    配置文件的前缀，如下就是：service-config-*.properties或者service-config-*.yaml，*号代表调用者指定，浏览器访问：http://localhost:8100/service-config/dev，就是访问https://github.com/latico/springcloud-config-center.git/config/helloworldConfig/service-config-dev.properties或者https://github.com/latico/springcloud-config-center.git/config/helloworldConfig/service-config-dev.yaml
    name: server-config-springcloud-git
  #安全认证配置
  security:
    user:
      name: admin
      password: admin
  cloud:
    config:
      server:
        prefix: service-config
        git:
          #          在如下git项目中
          uri: https://github.com/latico/springcloud-config-center.git
          #          git地址目录下里面的搜索目录路径
          searchPaths: config

#          把配置中心发布到注册中心
eureka:
  instance:
    preferIpAddress: true
    # 每隔10s发送一次心跳
    lease-renewal-interval-in-seconds: 10
    # 告知服务端30秒还未收到心跳的话，就将该服务移除列表
    lease-expiration-duration-in-seconds: 30
    #    eureka的管理页面中的注册客户端列表的status字段显示的内容，设置显示swagger
    statusPageUrl: http://${spring.security.user.name}:${spring.security.user.password}@${spring.cloud.client.ip-address:localhost}:${server.port}/swagger-ui.html
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8000/eureka/