#单机模式时
server:
  port: 9400

spring:
  application:
    name: service-invoker-zookeeper
  cloud:
    zookeeper:
#      连接zookeeper服务器的地址
      connectString: localhost:2181

#http编码配置
http:
  encoding:
    charset: UTF-8
    force: true
    enabled: true
