server:
  port: 9100
spring:
  application:
    name: service-invoker-stream-kafka
  cloud:
    stream:
      kafka:
        binder:
#          kafka的连接
          brokers: localhost:9092
#          zookeeper的连接
          zk-nodes: localhost:2181
          auto-create-topics: true
      bindings:
        #input是接收，注意这里不能再像前面一样写output了
        input:
          destination: stream-kafka

#          第二个接收
        myInput:
          destination: stream-kafka-my