#集群模式时的节点3启动配置
server:
  port: 9303

spring:
  application:
    name: service-provider-zookeeper
  cloud:
    zookeeper:
      #      连接zookeeper服务器的地址
      connectString: localhost:2181
      #      提供服务提供者自身的信息
      discovery:
        enabled: true
#        instanceHost: localhost
#        instancePort: ${server.port}
endpoints:
  restart:
    enabled: true
logging:
  level:
    org.apache.zookeeper.ClientCnxn: WARN
#http编码配置
http:
  encoding:
    charset: UTF-8
    force: true
    enabled: true
