server:
  port: 9002
spring:
  application:
    name: service-provider-eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/,http://localhost:8002/eureka/,http://localhost:8003/eureka/