#单机模式
server:
  port: 9100
spring:
  application:
    name: service-invoker-consul

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
#        serviceName: service-invoker-consul
#        register: false